### ISSUE TITLE
error on autodiff page

### ISSUE THREAD

**Issue by isaacgerg** [DouglasOrr/DouglasOrr.github.io#2]
The derivative on https://douglasorr.github.io/2021-11-autodiff/article.html doesn't look correct.

You have dy/dx = -2 y H(x) which I believe to be incorrect.  Should be -2 exp(-2x) H(x).

Sanity check here: https://www.wolframalpha.com/input/?i=dy%2Fdx+of+y%3Dexp%28-2+*+max%28x%2C+0%29%29

**Comment by DouglasOrr** [comment]
Hi Isaac! Thanks for taking the time to investigate & get in touch.

Actually, I think we might be on the same track - in my version, y is a placeholder for exp(-2 max(x, 0)). Then, since H(x) = 0 for x < 0, you can replace max(x, 0) with x, to get your better-simplified equation.

Another manual check against finite differences...

![image](https://user-images.githubusercontent.com/322002/140499442-35d79cbe-59e6-4a36-9ed8-7c133cc94cc3.png)

```python
import numpy as np
import matplotlib.pyplot as plt

xs = np.linspace(-2, 2, 1000)
ys = np.exp(-2 * np.maximum(xs, 0))

plt.plot(xs, ys, label=r"$y=e^{-2 \mathrm{max}(x, 0)}$")

dydx = -2 * ys * (xs > 0)

plt.plot(xs, dydx, label=r"$\frac{\partial y}{\partial x} = -2 y \mathrm{H}(x)$")

dydx_v2 = -2 * np.exp(-2 * xs) * (xs > 0)

plt.plot(xs, dydx_v2, label=r"$\frac{\partial y}{\partial x} = -2 e^{-2x} \mathrm{H}(x)$")

dydx_numeric = (ys[1:] - ys[:-1]) / (xs[1:] - xs[:-1])

plt.plot((xs[1:] + xs[:-1]) / 2, dydx_numeric, label=r"$\frac{\partial y}{\partial x} = \frac{\Delta y}{\Delta x}$ (finite difference)", lw=4, alpha=.25)

plt.legend(loc="lower left")
plt.xlabel("x")
plt.ylabel("y")
plt.title(r"Gradient check for $y=e^{-2 \cdot \mathrm{max}(x, 0)}$");
```

**Comment by isaacgerg** [comment]
I see now but missed this at first.  I simply took your initial function composition expression and did the chain rule on it to get dy/dx and noticed they didnt match.  I also didn't expect to see y on both sides of the equation.  But, looks like it worked out.  Thanks for following up!
